-- Table for users
CREATE TABLE users
(
    id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email    TEXT NOT NULL UNIQUE,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    bio      TEXT,
    image    TEXT
);

-- Table for articles
CREATE TABLE articles
(
    id              INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    slug            TEXT      NOT NULL UNIQUE,
    title           TEXT      NOT NULL,
    description     TEXT      NOT NULL,
    body            TEXT      NOT NULL,
    createdAt      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    favoritesCount INT       NOT NULL DEFAULT 0,
    authorID      BIGINT    REFERENCES users (id) ON DELETE SET NULL
);

-- Table for tags
CREATE TABLE tags
(
    id  INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tag TEXT NOT NULL UNIQUE
);

-- Table for article_tags (many-to-many relationship)
CREATE TABLE article_tags
(
    articleID INT REFERENCES articles (id) ON DELETE CASCADE,
    tagID     INT REFERENCES tags (id) ON DELETE CASCADE,
    PRIMARY KEY (articleID, tagID)
);

-- Table for favorites
CREATE TABLE favorites
(
    userID    BIGINT REFERENCES users (id) ON DELETE CASCADE,
    articleID INT REFERENCES articles (id) ON DELETE CASCADE,
    PRIMARY KEY (userID, articleID)
);

-- Table for comments
CREATE TABLE comments
(
    id         INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    articleID INT REFERENCES articles (id) ON DELETE CASCADE,
    userID    BIGINT REFERENCES users (id) ON DELETE CASCADE,
    body       TEXT      NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE follows
(
    followerID BIGINT REFERENCES users (id) ON DELETE CASCADE,
    followeeID BIGINT REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (followerID, followeeID)
);

-- Indexes for performance
CREATE INDEX idx_users_email ON users (email);
CREATE INDEX idx_users_username ON users (username);
CREATE INDEX idx_articles_author_id ON articles (authorID);
CREATE INDEX idx_comments_article_id ON comments (articleID);
CREATE INDEX idx_comments_user_id ON comments (userID);
