// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID             int32
	Slug           string
	Title          string
	Description    string
	Body           string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	FavoritesCount int32
	AuthorID       pgtype.Int8
}

type ArticleTag struct {
	ArticleID int32
	TagID     int32
}

type Comment struct {
	ID        int32
	ArticleID pgtype.Int4
	UserID    pgtype.Int8
	Body      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Favorite struct {
	UserID    int64
	ArticleID int32
}

type Follow struct {
	FollowerID int64
	FolloweeID int64
}

type Tag struct {
	ID  int32
	Tag string
}

type User struct {
	ID       int64
	Email    string
	Username string
	Password string
	Bio      pgtype.Text
	Image    pgtype.Text
}
